DROP DATABASE IF EXISTS nstweb;
CREATE DATABASE nstweb  DEFAULT CHARACTER SET utf8;
USE nstweb;
DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
 id INT(11) NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(255) NULL DEFAULT NULL,
 PASSWORD VARCHAR(255) NULL DEFAULT NULL,
 salt VARCHAR(255) NULL DEFAULT NULL,
 phone VARCHAR(255) NULL DEFAULT '',
 email VARCHAR(128) NULL DEFAULT NULL,
 born DATE NULL DEFAULT NULL,
 sex VARCHAR(64) NULL DEFAULT NULL,
 login_time TIMESTAMP NULL DEFAULT NULL,
 PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS role;
CREATE TABLE role(
 id INT(11) NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(255) NULL DEFAULT NULL,
 desc_ VARCHAR(255) NULL DEFAULT NULL,
 PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS permission;
CREATE TABLE permission(
 id INT(11) NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(255) NULL DEFAULT NULL,
 desc_ VARCHAR(255) NULL DEFAULT NULL,
 PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS user_role;
CREATE TABLE user_role(
 id INT(11) NOT NULL AUTO_INCREMENT,
 user_id INT(11) NULL DEFAULT NULL,
 role_id INT(11) NULL DEFAULT NULL,
 PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS role_permission;
CREATE TABLE role_permission(
 id INT(11) NOT NULL AUTO_INCREMENT,
 role_id INT(11) NULL DEFAULT NULL,
 per_id INT(11) NULL DEFAULT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS template;
CREATE TABLE template(
 id INT(11) NOT NULL AUTO_INCREMENT,
 PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS product;
CREATE TABLE product(
id INT(11) NOT NULL AUTO_INCREMENT,
user_id INT(11) NULL DEFAULT NULL,
title VARCHAR(100) NULL DEFAULT NULL,
STATUS INT(11) NOT NULL DEFAULT 0,
create_time TIMESTAMP NULL DEFAULT NULL,
comment_count INT(11) NOT NULL DEFAULT 0,
score DOUBLE NOT NULL DEFAULT 0,
temp_id  INT(11) NULL DEFAULT NULL,
scale FLOAT NOT NULL DEFAULT 0,
weight INT(11) NOT NULL DEFAULT 0,
color INT(11) NOT NULL DEFAULT 0,
PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS queue;
CREATE TABLE queue(
id INT(11) NOT NULL AUTO_INCREMENT,
user_id INT(11) NULL DEFAULT NULL,
product_id INT(11) NULL DEFAULT NULL,
STATUS INT(11) NOT NULL DEFAULT 0,
create_time TIMESTAMP NULL DEFAULT NULL,
comment_count INT(11) NOT NULL DEFAULT 0,
TYPE INT(11) NOT NULL DEFAULT 0,
scale FLOAT NOT NULL DEFAULT 0,
weight INT(11) NOT NULL DEFAULT 0,
color INT(11) NOT NULL DEFAULT 0,
PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS shidle;
CREATE TABLE shidle(
id INT(11) NOT NULL AUTO_INCREMENT,
user_id INT(11) NULL DEFAULT NULL,
product_id INT(11) NULL DEFAULT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS follow;
CREATE TABLE follow(
id INT(11) NOT NULL AUTO_INCREMENT,
user_id INT(11) NULL DEFAULT NULL,
follower_id  INT(11) NULL DEFAULT NULL,
create_time TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS COMMENT;
CREATE TABLE COMMENT(
id INT(11) NOT NULL AUTO_INCREMENT,
user_id INT(11) NULL DEFAULT NULL,
entity_type INT(11) NULL DEFAULT NULL,
target_id INT(11) NULL DEFAULT NULL,
content TEXT,
STATUS INT(11) NULL DEFAULT NULL,
create_time TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS message;
CREATE TABLE message(
id INT(11) NOT NULL AUTO_INCREMENT,
from_id INT(11) NULL DEFAULT NULL,
to_id INT(11) NULL DEFAULT NULL,
conversation_id VARCHAR(45) NULL DEFAULT NULL,
content TEXT,
STATUS INT(11) NULL DEFAULT NULL,
create_time TIMESTAMP NULL DEFAULT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS report;
CREATE TABLE report(
id INT(11) NOT NULL AUTO_INCREMENT,
from_id INT(11) NULL DEFAULT NULL,
target_id INT(11) NULL DEFAULT NULL,
entity_id INT(11) NULL DEFAULT NULL,
entity_type INT(11) NULL DEFAULT NULL,
STATUS INT(11) NULL DEFAULT NULL,
create_time TIMESTAMP NULL DEFAULT NULL,
remark  VARCHAR(255) NULL DEFAULT NULL,
PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;


