eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul-service
zuul:
  routes:
    api-a:
      path: /api-products/**
      serviceId: PRODUCTS-SERVICE
    api-b:
      path: /api-views/**
      serviceId: views-service