eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zuul-service
zuul:
  routes:
    api-a:
      path: /api-products/**
      serviceId: PRODUCTS-SERVICE
      sensitiveHeaders: "*"
    api-b:
      path: /api-views/**
      serviceId: views-service
      sensitiveHeaders: "*"
    api-c:
          path: /api-user/**
          serviceId: user-service
          sensitiveHeaders: "*"