eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: view-service
    thymeleaf:
        mode: LEGACYHTML5
        encoding: UTF-8
        content-type: text/html
        cache: false
